[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ISS_tools"
version = "0.1.0"
description = "Tools for parsing and annotating ISS/DALI output using Pfam"
readme = "README.md"
requires-python = ">=3.7"
authors = [{name="Liisa Holm", email="liisa.holm@helsinki.fi"}]
dependencies = [
    "notebook>=6.5.7",
    "pandas",
    "pip"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ISS_tools"]

[tool.setuptools.package-dir]
"" = "scripts"
ISS_tools = "ISS_tools"

[project.scripts]
pfamtool = "pfamtool:main"
dalitool = "dalitool:main"

[tool.setuptools]
py-modules = ["pfamtool", "dalitool"]
include-package-data = true

[project.optional-dependencies]
dev = [
    "ruff>=0.12.3",
    "pre-commit>=2.21",
]

visualization = [
    "bitstring",
    "logomaker",
    "matplotlib",
    "numpy",
    "plotly",
    "scipy",
    "seaborn"
]

[tool.ruff]
format.quote-style = "double" # Change this to "single" to have strings with ' sign instead.
